name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t sgoswamigeek/docker-react-demo -f Dockerfile.dev .
    
    - name: Run Tests
      run: docker run -e CI=true sgoswamigeek/docker-react-demo npm run test 

    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - 
      uses: docker/build-push-action@v2
      name: Build & push Docker image
      with:
        tags: ${{ secrets.DOCKER_USERNAME }}/docker-react-demo:latest
        builder: ${{ steps.buildx.outputs.name }}
        context: ./
        file: ./Dockerfile
        push: true